spring.application.name=pfe_sample
server.port=8089

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/test_pfe
spring.datasource.username=postgres
spring.datasource.password=P0stgr3SQL!2026#Secure

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect





spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigurationspring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration